spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharing-library?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kalswl99

  jpa:
    hibernate:
      ddl-auto: update
      show-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8383