server:
  port: 8383

spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/sharing-library?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: password



  jpa:
    hibernate:
      ddl-auto: update
      show-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info
    minji.sharinglibraryserver: debug
    org.springframework.web: debug
    sql: error


